#功能:
#>物品
#################################
#####       语言文件        #####
#################################
lang:
  default: "cn"                #默认语言(指不明确指定语言的情况下)
  error: "en"                  #错误时使用语言(指指定的语言配置不存在时使用的语言配置)
#################################
#####         描述          #####
#################################
description:
  - "&7- 重新读取config.yml"
  - "&7- 重新读取language.yml"
#################################
#####         配置          #####
#################################
editPer: "lib.items.edit"     #物品编辑权限

#################################
#####     物品获取类型      #####
#################################
#=========== 符号说明 ===========
#[可选] <必选> (整体)

#=========== 格式要求 ===========
#<文件名>:<类型名> <(<all/single>:<min次数>-<max次数>)/(<几率缩放目标值>/<最大几率>:<min数量>-<max数量>)>

#=========== 格式说明 ===========
#文件名  ->  指文件名
#类型名  ->  指类型名
#all/single  ->  取的方式,all指可重复取,single指不重复取
#min次数  ->  最小次数,>=0
#max次数  ->  最大次数,>=0且>=min
#几率缩放目标值  ->  几率缩放到的目标值.-1表示不缩放,必须>=0(-1除外),0将不会取到物品
#最大几率  ->  指最大几率,>0,物品被取到的可能性=物品的几率/最大几率
#min数量  ->  最小数量,>=0
#max数量  ->  最大数量,>=0且>=min

#=========== 格式异常 ===========
#物品类型不存在,配置有误,或其它异常将当作不存在此项来处理

#=========== 名词说明 ===========
#获取类型: 指获取物品的类型
#物品类型: 指物品配置的类型

#=========== 其它说明 ===========
#根据物品检测的机制,在根据几率配置的情况下:
#平均取到数量=几率缩放目标值/最大几率(avg=tar/max)
#min数量不应比平均取到数量大很多,否则后面的物品被取到几率会很大
#max数量不应比平均取到数量小很多,否则后面的物品被取到几率会很小
#比较合适的是min<avg<max
items:
  getType1:
    - "default:selBar all:1-1"