#################################
#####       物品(items)     #####
#################################
#=========== 符号说明 ===========
#[可选] <必选> (整体)

#=========== 名词说明 ===========
#物品配置: 指物品类型里的具体物品信息(调用服务端方法读取)

#################################
#####        物品类型       #####
#################################
#============ 方式一 ============
#inherits  ->  继承,可选
#其它变量,可按功能自行添加
#============ 方式二 ============
#chance  ->  几率,可选,默认为0,>=0
#物品配置  ->  服务端可读取的物品格式
#其它变量,可按功能自行添加

#=========== 方式说明 ===========
#方式一与方式二只能选取其一
#优先选择方式一(两种方式都存在时)

#=========== 格式异常 ===========
#物品数据与继承项都为空,物品数据读取异常,chance<0或其它异常将当作不存在此物品类型来处理

#################################
#####         继承项        #####
#################################
#=========== 格式要求 ===========
#[[插件名:]<文件名>:]<类型名> [目标缩放值]

#=========== 格式说明 ===========
#插件名  ->  指插件名,默认为此配置所属插件
#文件名  ->  指文件名,默认为此配置所属文件
#类型名  ->  指类型名
#目标缩放值  ->  几率的目标缩放值

#=========== 格式异常 ===========
#当作不存在此继承项来处理

#  - check 检测模式,仅在检测物品类型时用到
#    - 值为1表示仅检测物品ID,比如你希望检测羊毛,但不管是哪种颜色的
#    - 值为2表示检测物品ID与伤害值与ItemMeta,比如你希望检测染料骨粉,但不希望其它染料也满足,再比如你希望检测2把铁剑,但不希望耐久快没了的也满足或附魔的也满足
#此外,可以手动修改配置中的物品数量(比如修改为300)

#################################
#####    物品类型配置样例   #####
#################################
testItem:                       #物品类型名,同一个文件内的类型名不可重复.
  inherits:                     #继承列表,默认为空,加上后不能再加物品配置与几率.
  chance: 0                     #几率,默认为0,0将不会取到.几率必须>=0.有物品配置的类型才能加.
  type: STONE