#################################
#####       物品(items)     #####
#################################
#=========== 符号说明 ===========
#[可选] <必选> (整体)

#=========== 名词说明 ===========
#物品配置: 指物品类型里的具体物品信息(调用服务端方法读取)

#################################
#####        物品类型       #####
#################################
#============ 方式一 ============
#inherits  ->  继承,可选
#其它变量,可按功能自行添加
#============ 方式二 ============
#chance  ->  几率,可选,默认为1,>=0
#getType  ->  动态获取类型,格式'插件名 获取器名 [变量]'
#其它变量,可按功能自行添加
#============ 方式三 ============
#chance  ->  几率,可选,默认为1,>=0
#物品配置  ->  服务端可读取的物品格式
#其它变量,可按功能自行添加

#=========== 方式说明 ===========
#单个物品配置只能选取一种方式!
#方式优先级: 方式一>方式二>方式三
#方式检测方法: 有'inherits'为方式一,有'getType'为方式二,其它为方式三

#=========== 格式异常 ===========
#物品数据与继承项都为空,物品数据读取异常,chance<0或其它异常将当作不存在此物品类型来处理

#################################
#####         继承项        #####
#################################
#=========== 格式要求 ===========
#[<文件名>:]<类型名> [目标缩放值]

#=========== 格式说明 ===========
#文件名  ->  指文件名,默认为此配置所属文件
#类型名  ->  指类型名
#目标缩放值  ->  几率的目标缩放值

#=========== 格式异常 ===========
#当作不存在此继承项来处理

#################################
#####    物品类型配置样例   #####
#################################
testItem:                       #物品类型名,同一个文件内的类型名不可重复.
  inherits:                     #继承列表,默认为空,加上后不能再加物品配置与几率.
  chance: 1                     #几率,默认为1,0将不会取到.几率必须>=0.有物品配置的类型才能加.
  type: STONE